INSERT INTO
  "user" (
    id,
    first_name,
    last_name,
    email,
    password,
    type,
    auth_source,
    agency_id,
    created_at
  )
VALUES
  (
    gen_random_uuid(),
    'Admin',
    'User',
    'admin@example.com',
    '$2a$12$GL73kREKYHe8O6pMJ/4zuOOqT0KiPb7Xo7gty0w/8WOjKnOAgWFuS',
    'ADMIN',
    '{}',
    (
      SELECT
        id
      FROM
        "agency"
      WHERE
        name = 'VK Admin'
    ),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Tour',
    'Agency',
    'tour_agency@example.com',
    '$2a$12$GL73kREKYHe8O6pMJ/4zuOOqT0KiPb7Xo7gty0w/8WOjKnOAgWFuS',
    'TOUR_AGENCY',
    '{}',
    (
      SELECT
        id
      FROM
        "agency"
      WHERE
        name = 'Tour Agency Alpha'
    ),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Event',
    'Agency',
    'event_agency@example.com',
    '$2a$12$GL73kREKYHe8O6pMJ/4zuOOqT0KiPb7Xo7gty0w/8WOjKnOAgWFuS',
    'EVENT_AGENCY',
    '{}',
    (
      SELECT
        id
      FROM
        "agency"
      WHERE
        name = 'Event Agency Beta'
    ),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Tour',
    'Organizer',
    'tour_organizer@example.com',
    '$2a$12$GL73kREKYHe8O6pMJ/4zuOOqT0KiPb7Xo7gty0w/8WOjKnOAgWFuS',
    'TOUR_ORGANIZER',
    '{}',
    (
      SELECT
        id
      FROM
        "agency"
      WHERE
        name = 'Tour Agency Alpha'
    ),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Event',
    'Organizer',
    'event_organizer@example.com',
    '$2a$12$GL73kREKYHe8O6pMJ/4zuOOqT0KiPb7Xo7gty0w/8WOjKnOAgWFuS',
    'EVENT_ORGANIZER',
    '{}',
    (
      SELECT
        id
      FROM
        "agency"
      WHERE
        name = 'Event Agency Beta'
    ),
    NOW()
  ) ON CONFLICT (email) DO NOTHING;